server:
  port: 80

# https://docs.spring.io/spring-boot/docs/2.2.6.RELEASE/reference/htmlsingle/#templating-properties
spring:
  freemarker:
    cache: false
    charset: UTF-8
    enabled: true
    suffix: .ftl
    template-loader-path: classpath:/templates/

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_boot?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
    username: root
    password: 123456

  # dubbo will use
  application:
    name: spring-boot-demo

embedded:
  zookeeper:
    port: 2181

dubbo:
  registry:
    address: zookeeper://127.0.0.1:${embedded.zookeeper.port}
    file: ${user.home}/dubbo-cache/${spring.application.name}/dubbo.cache
  protocol:
    name: dubbo
    port: -1
  application:
    name: ${spring.application.name}
  scan:
    base-packages: com.zeroq6.spring_boot.provider

#
demo:
  service:
    version: 1.0.0


mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: sqlmap/**/*Dao.xml
  type-aliases-package: com.zeroq6.**.domain

logging:
  file:
    name: spring_boot.log
  level:
    root: warn
    com.zeroq6: debug

xss:
  enabled: true
  excludes:
  urlPatterns: /*


